### ISSUE TITLE
@Function eclipse auto-import

### ISSUE THREAD

**Issue by nicholas22** [peichhorn/lombok-pg#21] opened 2011-10-01 08:36 UTC
I'm getting a minor bug, when a type is unused in a file and you use it within a @function block, the Eclipse IDE Ctrl-Shift-O (auto-import) does not discover it. In fact, if you have imported it and do auto-import as above, it is actually removed from imports!!! Workaround at the moment is to not use Ctrl+Shift+O... Idea: have a look at how @SneakyThrows does it (you mentioned some fixed position info...)

**Comment by peichhorn** [comment] 2011-10-03 12:56
After a quick look the main difference is, that none of the lombok transformation generate anonymous or inner classes and that is why Ctrl+Shift+O works. Ctrl+Shift+O also works in @WriteLock which is structure-wise very similar to @SneakyThrows.
This means this issue is caused by the fact that the content of the annotated method will be moved inside a anonymous or inner class.
Well it's a start, but may take a while.

**Comment by peichhorn** [comment] 2011-11-13 14:16
fixed with the upgrade to lombok 0.10.3 including the usability fixes provided by Jappe van der Hel
 see issue #49

I will let you now when I upload a new edge release.

**Closed as completed by peichhorn** 2011-11-13 14:16 UTC
Labels: type:bug, compiler:ecj

**Comment by nicholas22** [comment] 2011-11-13 19:23
Excellent, let me know
